import {motion,useReducedMotion} from 'framer-motion';
import {useState} from 'react';
import Slider from './Slider';
const layers=[
 {name:'Origin',verb:'Where a structure begins.',example:'The central point provides a starting reference. This is an illustration of origin, not a new particle-creation law.',color:'#76e7df'},
 {name:'Authorship',verb:'How a structure develops.',example:'A connected form grows outward from its starting reference. Authorship names the proposed account of development, not a conscious author.',color:'#76a9ff'},
 {name:'Sovereignty',verb:'What keeps a structure stable.',example:'A recognizable relationship persists while the form changes. Physical stability would still require equations and perturbation tests.',color:'#b69afc'},
 {name:'Warp',verb:'How a structure transforms.',example:'A circle deforms without disconnecting. This illustrates transformation, not spacetime curvature or faster-than-light travel.',color:'#f0bf91'}
];
export function Identity({observation,running}:{observation:number;running:boolean}) {
 const [selected,setSelected]=useState(0),reduced=useReducedMotion();
 return <section className="identity-module"><span className="badge proposal">SEFI / IDENTITY AS GEOMETRY</span><div className="identity-layout"><div className="identity-cards">{layers.map((l,i)=><button key={l.name} onClick={()=>setSelected(i)} aria-pressed={selected===i} className={selected===i?'active':''}><strong style={{color:l.color}}>{l.name}</strong><span>{l.verb}</span></button>)}</div><div className="identity-visual"><svg viewBox="0 0 300 220" aria-label={`${layers[selected].name} conceptual geometry`} role="img">{[0,1,2].map(i=><motion.ellipse key={`${selected}-${i}`} cx="150" cy="110" rx={42+i*20} ry={selected===3?20+i*8:42+i*7} fill="none" stroke={layers[selected].color} strokeWidth={selected===2?2:1} opacity={.9-i*.2} animate={running&&!reduced?{rotate:[i*40,i*40+360],scale:[1,1+observation*.13,1]}:{rotate:i*40,scale:1+observation*.13}} transition={{duration:12+i*4,repeat:Infinity,ease:'linear'}} style={{transformOrigin:'150px 110px'}}/>)}<circle cx="150" cy="110" r={selected===0?7:3} fill={layers[selected].color}/></svg><p aria-live="polite"><strong>{layers[selected].name}: </strong>{layers[selected].example}</p></div></div><p>These four layers are proposed organizing concepts. The shapes are teaching illustrations, not measured identity observables.</p></section>;
}
export function Coupling({observation,running}:{observation:number;running:boolean}) {
 const [coupling,setCoupling]=useState(55),[drive,setDrive]=useState(40),[identityDrive,setIdentityDrive]=useState(30),reduced=useReducedMotion();
 const geometry=.8+drive/250+identityDrive*coupling/100/500;
 const identity=.85+identityDrive/250+drive*coupling/100/500;
 return <section className="coupling-module"><span className="badge proposal">DEFI / ILLUSTRATIVE COUPLING</span><div className="coupling-stage"><motion.div className="geometry-system" animate={running&&!reduced?{scale:[geometry,geometry+.025*observation,geometry],borderRadius:['25%','45%','25%']}:{scale:geometry,borderRadius:'35%'}} transition={{duration:5,repeat:Infinity}}><span>Geometry layer</span></motion.div><div className="coupling-link" style={{opacity:.2+coupling*.008}} aria-label="Mutual influence">↔</div><motion.div className="identity-system" animate={running&&!reduced?{scale:[identity,identity+.025*observation,identity]}:{scale:identity}} transition={{duration:5,repeat:Infinity}}><span>Identity layer</span></motion.div></div><div className="three-controls"><Slider label="Change the geometry" value={drive} min={0} max={100} onChange={setDrive}/><Slider label="Change the identity motif" value={identityDrive} min={0} max={100} onChange={setIdentityDrive}/><Slider label="Illustrative coupling" value={coupling} min={0} max={100} unit="%" onChange={setCoupling}/></div><p>Change either layer and watch the other respond. At zero coupling, each control affects only its own layer. This is a teaching relationship, not a derived DEFI field law.</p></section>;
}
